### ISSUE TITLE
ESLint dosen't work

### ISSUE THREAD

**Issue by YubaC** [Yuba-Technology/Archives#11]
### Prerequisites

- [X] I have [searched](https://github.com/Yuba-Technology/Archives/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Yuba-Technology/Archives/blob/main/.github/CONTRIBUTING.md)

### Where does the bug occur?

Frontend

### Describe the issue

ESLine dosen't work when I run `npm run lint`.

```
$ npm run lint

> archives@1.0.0 lint
> eslint . --cache --cache-location .cache/.eslintcache --report-unused-disable-directives --ext .vue,.js,.jsx,.cjs,.mjs --ignore-path .gitignore


Oops! Something went wrong! :(

ESLint: 8.57.0

Error: ESLint configuration of processor in '.eslintrc.cjs#overrides[2]' is invalid: 'node/file' was not found.
    at ConfigValidator.validateProcessor (D:\Archives\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2137:19)
    at ConfigValidator.validateConfigArray (D:\Archives\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2225:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (D:\Archives\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3985:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (D:\Archives\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3791:21)
    at FileEnumerator._iterateFilesRecursive (D:\Archives\node_modules\eslint\lib\cli-engine\file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (D:\Archives\node_modules\eslint\lib\cli-engine\file-enumerator.js:299:49)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (D:\Archives\node_modules\eslint\lib\cli-engine\cli-engine.js:797:48)
    at ESLint.lintFiles (D:\Archives\node_modules\eslint\lib\eslint\eslint.js:551:23)

```

### Reduced test cases

Change these lines:

```js
        {
            files: ["wewbpack.*.js"],
            plugins: ["node"],
            processor: "node/file"
        },
```

to:

```js
        {
            files: ["webpack.*.js"],
            plugins: ["node"],
            env: {
                node: true
            }
        },
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Archives are you using?

None

**Comment by Begonia-Aquaphle** [comment]
Hi @YubaC! 👋
Thanks for opening this issue. We will get back to you soon.
